[LPN-132] Refetch callers
EnMarche/Data-Corner pull request #1005
Opened 2022-02-03 10:21 UTC by XavierLac

2022-02-03 12:41 UTC, nicolaszil commented on src/components/Phoning/CreateEdit/CreateEdit.js
> +      refetchCallers()
du coup tu peux à la place de ça, rajouter `onUpdateResolve()` en dessous de `onCreateResolve()`

2022-02-03 12:41 UTC, nicolaszil commented on src/components/Phoning/CreateEdit/CreateEdit.js
> +  refetchCallers: PropTypes.func.isRequired,
nom de la proptype

2022-02-03 12:41 UTC, nicolaszil commented on src/components/Phoning/CampaignDetail/CampaignDetail.js
> +          refetchCallers={refetchCallers}
si le `refetchCallers` doit être appelé après modification d'une campagne, le nom de la prop c'est `onUpdateResolve`

2022-02-03 12:42 UTC, nicolaszil reviewed
review

2022-02-03 12:42 UTC, nicolaszil requested changes
review

2022-02-03 12:47 UTC, nicolaszil commented on src/components/Phoning/CampaignDetail/CampaignDetail.js
> +          refetchCallers={refetchCallers}
et du coup je me pose la question pour les 2 autres onglets (tabs), est-ce qu'on doit pas aussi raffraichir les infos ?

2022-02-04 07:52 UTC, XavierLac commented on src/components/Phoning/CampaignDetail/CampaignDetail.js
> +          refetchCallers={refetchCallers}
Je regarde pour les 2 autres onglets

2022-02-04 08:43 UTC, nicolaszil commented on src/components/Phoning/CreateEdit/CreateEdit.js
> +      onUpdateResolve()
la fonction resolve sera appélée soit par la modale de create soit par celle de update, mais pas les 2 à la fois.
c'est l'un ou l'autre ;)

`!campaign ? onCreateResolve() : onUpdateResolve()`

2022-02-04 08:46 UTC, XavierLac commented on src/components/Phoning/CreateEdit/CreateEdit.js
> +      onUpdateResolve()
True, merci

2022-02-04 13:46 UTC, merged