[LPN-458] Read New: publishing actions
EnMarche/Data-Corner pull request #1207
Opened 2022-03-16 06:03 UTC by gasipari

2022-03-16 08:17 UTC, XavierLac commented on src/components/News/ReadCTA.js
> +      getNextPageParam,
Il m'a l'air inutilisé ici le getNextPageParam

2022-03-16 08:23 UTC, XavierLac commented on src/components/News/styles.js
>      color: ${theme.palette.campaign.button.color.main};
Au début de la palette, tu peux trouver les couleurs dont tu as besoin theme.palette.button.color.main ou theme.palette.button.background.main. Je te laisse regarder. Le chemin avec campaign est normalement destiné à la feature Phoning

2022-03-16 08:29 UTC, XavierLac commented on src/components/News/ReadCTA.js
> +        <Body component={'p'} sx={{ mt: 1 }}>
On peut enlever les accolades ici => component='p'

2022-03-16 12:21 UTC, nicolaszil commented on src/providers/styles.js
> +    redSecondary: '#CC0613',
si x'est une error de formulaire il faut la mettre dans le noeud "form", sinon peut être créer un noeud error
prévoir sûrement aussi un point avec Xavier (et moi en support) pour t'expliquer la stratégie de nommage sur le  theme

2022-03-16 12:22 UTC, nicolaszil commented on src/components/News/styles.js
> +    border: ${ispublished === 'true' ? `1px ${theme.palette.redSecondary} solid` : `1px ${theme.palette.main} solid`};
ici je pense que tu veux tester un boolean donc `true` et non `'true'`

2022-03-16 12:24 UTC, nicolaszil commented on src/components/News/styles.js
> +    border: ${ispublished === 'true' ? `1px ${theme.palette.redSecondary} solid` : `1px ${theme.palette.main} solid`};
plus court : 
border: 1px ${isPublished ? theme.palette.redSecondary : theme.palette.main} solid;

2022-03-16 12:26 UTC, nicolaszil commented on src/components/News/styles.js
> +      color: ${theme.palette.whiteCorner};
@XavierLac tu te souviens si on a pas un spécifique dans l'app ?
`whiteCorner` c'est pas un reliquat du passé ?

2022-03-16 12:28 UTC, nicolaszil commented on src/components/News/constants.js
> +  'Lorsqu’elle est publiée, une actualité est visible de vos militants sur l’application mobile.'
Les constant sont en lowerCamelCase sur quasi tout le projet (en tout cas sur les composants)

2022-03-16 12:28 UTC, nicolaszil commented on src/components/News/constants.js
> +// READ CTA
On avait défini de ne pas laisser de commentaires dans le code, hormis d'exceptionnels `// TODO: ...`

2022-03-16 12:29 UTC, nicolaszil commented on src/components/News/constants.js
> +  'Lorsqu’il existe, un bouton s’affiche en bas de l’actualité. Ajoutez-en un en la modifiant.'
Tout ce qui est contenu texte statique est dans un objet `messages` scopé au composant

2022-03-16 12:31 UTC, nicolaszil commented on src/components/News/ReadModal.js
> +  const isPublished = news?.status ? true : false
tu peux englober d'un useMemo pour la perf quand `news` change (évite les re-render inutiles)

2022-03-16 12:33 UTC, nicolaszil commented on src/components/News/ReadModal.js
> +`
On distingue les éléments de Layouting (div, container etc..) des éléments de texte (Typography, span...)
Donc ici `color` doit être utilisé avec une `<Typography>` de préféence avec `sx`

2022-03-16 12:34 UTC, nicolaszil commented on src/components/News/ReadModal.js
> +  color: ${theme.palette.gray600};
idem que le commentaire ci-dessous

2022-03-16 12:37 UTC, nicolaszil commented on src/components/News/ReadCTA.js
> +        sx={{ display: 'flex', alignItems: 'center', justifyContent: 'flex-end' }}
les props que tu passes ici dans sx peuvent être donnée directement à `<Grid container`

2022-03-16 12:38 UTC, nicolaszil commented on src/components/News/ReadCTA.js
> +          {isPublication ? NEWS_READ_PUBLISH_TEXT : NEWS_READ_CTA_TEXT}
`hasPublication` pour une meilleure compréhension, si tu veux bien dire "a t-il une publication"
mieux pour la compréhension au niveau fonctionnel

2022-03-16 12:47 UTC, nicolaszil commented on src/components/News/ReadCTA.js
> +  const hasCTA = news.url && news.urlLabel
il faut cast en boolean car si ton `news.url` est undefined tu n'auras pas false comme valeur mais `undefined`
`!!(news.url && news.urlLabel)`

2022-03-16 12:48 UTC, nicolaszil commented on src/components/News/ReadCTA.js
> +  const isPublished = news.status
cast boolean `!!news.status`

2022-03-16 12:49 UTC, nicolaszil commented on src/components/News/ReadCTA.js
> +  const isPublication = mode === 'publication'
c'est une bonne idée le `mode` mais dans ce cas la valeur (publication et autres) doit être un enum ou dans une constant
exemple : `const isPublication = mode === CTAModes.publication`
(j'ai inventé 'CTAModes' mais tu peux mettre ce qui est parlant pour la feature)

2022-03-16 12:50 UTC, nicolaszil commented on src/components/News/ReadCTA.js
> +      closeModal()
par cohérence avec le reste du code, ce serait préférable de mettre `handleCllose` et non `closeModal`

2022-03-16 12:51 UTC, nicolaszil requested changes
review

2022-03-17 08:47 UTC, gasipari commented on src/providers/styles.js
> +    redSecondary: '#CC0613',
fixed

2022-03-17 09:12 UTC, gasipari commented on src/components/News/ReadModal.js
> +  const isPublished = news?.status ? true : false
@nicolaszil 
quelque chose comme 
`const unMemoizedPublished = () => (news?.status ? true : false); 
const isPublished = useMemo(unMemoizedPublished, [news])`

ou utiliser React.memo sur tout le composant ?

2022-03-17 09:20 UTC, nicolaszil commented on src/components/News/ReadModal.js
> +  const isPublished = news?.status ? true : false
useMemo te memoize la valeur que retourne ta fonction, du coup si ta prop change, pas de nouveau calcul inutile.
dans ton cas c'est : 
`const isPublished = useMemo(() => news?.status ? true : false, [news?.status])`

2022-03-17 09:44 UTC, merged