Edit news
EnMarche/Data-Corner pull request #641
Opened 2021-11-29 14:29 UTC by XavierLac

2021-11-29 17:14 UTC, jbcazaux commented on src/components/News/News.js
> +  // Open read modal
pas de commentaires, plutot du code lisible, donc renomme la méthode si ce n est pas suffisament clair

2021-11-29 17:15 UTC, jbcazaux commented on src/components/News/ReadModal.js
> +  handleOpenEditModal: PropTypes.func,
pas en required les props ?

2021-11-29 22:10 UTC, nicolaszil commented on src/components/News/CreateEditModal.js
> +                  id="status"
cet id est-il utile ?

2021-11-30 08:22 UTC, XavierLac commented on src/components/News/CreateEditModal.js
> +                  id="status"
Oui, on ne peut pas checker la checkbox s'il n'est pas là

2021-11-30 08:54 UTC, nicolaszil commented on src/ui/TextField/TextField.js
> +  <>
ce fragment est inutile

2021-11-30 08:58 UTC, nicolaszil commented on src/components/News/CreateEditModal.js
> +                  id="status"
formik gère d'abord le name, l'id n'est qu'un secours
il faut utiliser de préférence le name et non l'id dans les formulaires

2021-11-30 09:00 UTC, nicolaszil requested changes
changer les id de formulaire par des name

2021-11-30 09:34 UTC, nicolaszil commented on src/ui/TextField/TextField.test.js
> +    <div className="mui-TextField-mock" {...props} error="false" />
tu peux pas faire couler tes props dans un noeud html
le mieux est de les mettre nomément dans le className, à l'aide backticks

2021-11-30 09:34 UTC, nicolaszil commented on src/ui/TextField/TextField.js
> +      id={label}
l'id ne sert à rien, à éviter dans les formulaires, sauf usage très spécifique

2021-11-30 09:36 UTC, nicolaszil requested changes
review

2021-11-30 13:33 UTC, nicolaszil requested changes
Review

2021-11-30 14:02 UTC, nicolaszil approved these changes

2021-11-30 14:10 UTC, merged