[EM-1799] new menu
EnMarche/Data-Corner pull request #731
Opened 2021-12-14 17:22 UTC by XavierLac

2021-12-17 11:10 UTC, jbcazaux commented on src/components/PageContent/PageContent.js
> +    width: 100%;
flex: 1 c est mieux que width 100%

2021-12-17 11:11 UTC, jbcazaux commented on src/components/Scopes/Scopes.js
> +  width: 243px;
c est précis : )

2021-12-17 11:11 UTC, jbcazaux commented on src/components/Scopes/Scopes.js
> +                width: '243px',
c est le meme 243 ?

2021-12-17 11:12 UTC, XavierLac commented on src/components/Scopes/Scopes.js
> +  width: 243px;
Pixel perfect :)

2021-12-17 11:12 UTC, jbcazaux commented on src/components/Scopes/Scopes.js
> +                key={i}
on doit pouvoir utiliser le nom du scope genre userScope.code

2021-12-17 11:13 UTC, XavierLac commented on src/components/Scopes/Scopes.js
> +                width: '243px',
Non, pas le même composant. Le précédent s'applique au bouton de sélection des scopes et celui-ci au composant Menu. Il faut que je l'applique à une class native MUI

2021-12-17 11:13 UTC, jbcazaux commented on src/components/Sidebar/Desktop.js
> +    <img src={banner} alt="Macron photo" />
'Emmanuel Macron' 
photo c est en trop, il y a deja IMG

2021-12-17 11:15 UTC, XavierLac commented on src/components/PageContent/PageContent.js
> +    width: 100%;
Done

2021-12-17 11:30 UTC, nicolaszil commented on src/components/Scopes/Scopes.js
> +const AreaTypography = styled(Typography)`
pas besoin de mettre AreaTypography, tu peux mettre Area direct

2021-12-17 11:30 UTC, nicolaszil commented on src/components/Scopes/Scopes.js
> +const ScopeTypography = styled(Typography)`
pas besoin de mettre vTypography, tu peux mettre Scope direct

2021-12-17 11:31 UTC, nicolaszil commented on src/components/Scopes/Scopes.js
> +            }}
on avait pas dit que à partir de 2 propriétés, on mettait la surcharge dans un styled ?

2021-12-17 11:32 UTC, nicolaszil commented on src/components/Scopes/Scopes.js
> +                }}
là c'est beaucoup trop gros il ne faut pas le mettre dans le JSX, il faut créer un styled

2021-12-17 11:33 UTC, nicolaszil commented on src/components/Sidebar/Branding.js
> +  `
la height 12px c'est pas bon, soit c'est le conteneur qui doit faire 12px, soit il faut mettre un padding ;)

2021-12-17 11:34 UTC, nicolaszil commented on src/components/Sidebar/Branding.js
> +    </BetaWrapper>{' '}
&nbsp;

2021-12-17 11:34 UTC, nicolaszil commented on src/components/Sidebar/Desktop.js
> +    }}
styled

2021-12-17 11:35 UTC, nicolaszil commented on src/components/Sidebar/Desktop.js
> +    <img src={frenchFlag} alt="drapeau france" />
pas de balise img. Il faut créer un composant SVG comme vu ensemble il y a qq semaines.
tu as des exemples

2021-12-17 11:36 UTC, nicolaszil commented on src/components/Sidebar/MentionsLegales.js
> +        <Ul>
le composant Menu n'était pas adapté ?

2021-12-17 11:37 UTC, nicolaszil commented on src/components/Sidebar/MentionsLegales.js
> +          <Li>
le composant MenuItem n'était pas adapté ?

2021-12-17 11:37 UTC, nicolaszil commented on src/components/Sidebar/Mobile.js
> +    }}
styled

2021-12-17 11:38 UTC, nicolaszil commented on src/components/Sidebar/Sidebar.js
> +`
on met container now, plus Wrapper ;)

2021-12-17 11:38 UTC, nicolaszil commented on src/components/Sidebar/Sidebar.js
> +        }}
styled(Nav)

2021-12-17 11:39 UTC, nicolaszil commented on src/components/Sidebar/Sidebar.js
> +        }}
styled('main')

2021-12-17 11:39 UTC, nicolaszil requested changes
review

2021-12-17 12:45 UTC, XavierLac commented on src/components/Sidebar/Branding.js
> +  `
C'est le conteneur justement

2021-12-19 21:41 UTC, jbcazaux commented on src/components/Scopes/Scopes.js
> +            {filteredScopes?.length > 1 && <Divider sx={{ bgcolor: 'menu.background.active' }} />}
vu la definition c est pas possible que filteredScopes soit null, tu peux virer le ?

2021-12-19 21:42 UTC, jbcazaux commented on src/components/Scopes/Scopes.js
> +            {filteredScopes?.map(userScope => (
pareil sur tous les "?" des filteredScopes

2021-12-19 21:42 UTC, jbcazaux commented on src/components/Scopes/Scopes.js
> +                {userScope?.zones?.length === 1 && (
pareil ca peut pas etre null ca, faut pas mettre des ? a tort et a travers

2021-12-19 21:43 UTC, jbcazaux commented on src/components/Scopes/Scopes.js
> +                {userScope?.zones?.length === 1 && (
a toi de voir pour le zone?

2021-12-20 09:11 UTC, merged