Good bye jsx
EnMarche/Data-Corner pull request #775
Opened 2021-12-21 13:31 UTC by XavierLac

2021-12-21 17:05 UTC, jbcazaux commented on webpack.config.js
> +      extensions: ['.js'],
L77 aussi

2021-12-21 17:10 UTC, XavierLac commented on webpack.config.js
> +      extensions: ['.js'],
Le build ne fonctionne plus si j'enlève la ligne 77

2021-12-21 17:17 UTC, XavierLac commented on src/ui/icons/BarChart.js
> +export const BarChart = ({ alt }) => (
@nicolaszil Pas réussi à faire tourner avec SvgIcon mais je le laisse si tu veux qu'on regarde demain

2021-12-21 17:45 UTC, nicolaszil commented on src/components/NoMatch/NoMatch.js
> +          Retournez à l&apos;accueil
message

2021-12-21 17:45 UTC, nicolaszil commented on src/components/NoMatch/NoMatch.js
> +        L&apos;URL recherchée <strong>{location.pathname}</strong> n&apos;existe pas ou vous n&apos;avez pas les droits
message

2021-12-21 17:47 UTC, nicolaszil commented on src/components/Scopes/ScopesPage/ScopesPage.js
> +  },
passe le theme directement là haut

```
const Beta = styled('span')(({ theme ) => '
....
'
```

2021-12-21 17:48 UTC, nicolaszil commented on src/components/Scopes/ScopesPage/ScopesPage.js
> +`
theme direct en haut, voir comm plus haut

2021-12-21 17:49 UTC, nicolaszil commented on src/ui/icons/BarChart.js
> +export const BarChart = ({ alt }) => (
ok on voit ça ensemble

2021-12-21 17:50 UTC, nicolaszil commented on src/ui/icons/BarChart.js
> +export const BarChart = ({ alt }) => (
c'est parce que il te manque les props à passer, regarde les autres composants

2021-12-21 17:50 UTC, nicolaszil requested changes
review

2021-12-22 07:07 UTC, XavierLac commented on src/components/Scopes/ScopesPage/ScopesPage.js
> +  },
Les breakpoints ne fonctionnent pas en dehors de la version objet

2021-12-22 07:07 UTC, XavierLac commented on src/components/Scopes/ScopesPage/ScopesPage.js
> +`
Idem

2021-12-27 10:03 UTC, nicolaszil approved these changes

2021-12-27 10:05 UTC, merged